### ISSUE TITLE
Use as a library?

### ISSUE THREAD

**Issue by retr0h** [arsham/figurine#5]
Any chance this can be extended to be used as a library in other go projects?

**Comment by arsham** [comment]
Thanks for the suggestion. Now you can use it as a library (see c4f1d38d07ed5a):
```go
if err := figurine.Write(os.Stdout, input, fontName); err != nil {
	log.Fatal(err)
}
```
Please do let me know if you have a better suggestion regarding this API.

**Comment by smileart** [comment]
@arsham I imported `figurine` and did exactly as was suggested here, but got no output and error `statik/fs: no zip data registered` which refers to an open issue: https://github.com/rakyll/statik/issues/32 I guess.

Not exactly sure what can I do on my side, as a library user.

**Comment by dolmen** [comment]
statik allows only one directory to be registered for the whole program. This is by design as it is a very lightweight tool.
If you use statik in a library, users of the library will not be able to use statik anywhere else in the program. And statik doesn't (yet) warn about that.

So I think it would be more appropriate to use another solution for your library.
